# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252dc93ec0a29e65fc7d9c285e647221aab955753450bb85c08930de15e268ab9bb342202f80413def852ccdf0ffd67912b95a4f35e8b0492133e059e17be239

test:
  secret_key_base: c3375d6deadc32d3ae7a4b8a24d419d4da5d3fa84084b5e554e735bd68555c7d5c4d179da562185ac18615396b0c17d157e17425313c322738712f5cb3d5ad24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
